openapi: 3.0.3
info:
  title: Timeline API Token Auth
  version: 1.0.0
paths:
  /token:
    post:
      summary: Issue access token
      description: Issues a JWT access token when a valid client secret is provided.
      parameters:
        - in: header
          name: X-Client-Secret
          required: true
          schema:
            type: string
        - in: header
          name: Origin
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Token issued
          content:
            application/json:
              schema:
                type: object
                required: [access_token, token_type, expires_in]
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                    example: Bearer
                  expires_in:
                    type: integer
                    example: 900
        "401":
          description: Invalid client secret
        "429":
          description: Rate limit exceeded
  /health:
    get:
      summary: Health check (protected)
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Healthy
        "401":
          description: Unauthorized
  /events:
    get:
      summary: List events (protected)
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Events list
        "401":
          description: Unauthorized
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
